# Logfile created on 2022-06-04 08:39:33 +0000 by logger.rb/v1.4.2
{"severity":"ERROR","time":"2022-06-04T08:39:33.480Z","correlation_id":"41549056ab7dca97f88c80c05dabc5a1","exception.class":"Sidekiq::Worker::EnqueueFromTransactionError","exception.message":"`AuthorizedProjectUpdate::ProjectRecalculateWorker.perform_async` cannot be called inside a transaction as this can lead to\nrace conditions when the worker runs before the transaction is committed and\ntries to access a model that has not been saved yet.\n\nUse an `after_commit` hook, or include `AfterCommitQueue` and use a `run_after_commit` block instead.\n","exception.backtrace":["config/initializers/forbid_sidekiq_in_transactions.rb:25:in `block (2 levels) in \u003cmodule:NoEnqueueingFromTransactions\u003e'","app/services/projects/create_service.rb:152:in `setup_authorizations'","app/services/projects/create_service.rb:124:in `after_create_actions'","app/services/projects/create_service.rb:76:in `block in execute'","lib/gitlab/application_context.rb:100:in `block in use'","lib/gitlab/application_context.rb:100:in `use'","lib/gitlab/application_context.rb:46:in `with_context'","app/services/projects/create_service.rb:75:in `execute'","app/services/concerns/measurable.rb:35:in `execute'","lib/gitlab/database_importers/self_monitoring/project/create_service.rb:59:in `create_project'","app/models/concerns/stepable.rb:14:in `call'","app/models/concerns/stepable.rb:14:in `block in execute_steps'","app/models/concerns/stepable.rb:13:in `each'","app/models/concerns/stepable.rb:13:in `inject'","app/models/concerns/stepable.rb:13:in `execute_steps'","lib/gitlab/database_importers/self_monitoring/project/create_service.rb:27:in `execute'","(eval):3:in `block (2 levels) in run_file'","lib/gitlab/database/load_balancing/connection_proxy.rb:119:in `block in write_using_load_balancer'","lib/gitlab/database/load_balancing/load_balancer.rb:112:in `block in read_write'","lib/gitlab/database/load_balancing/load_balancer.rb:172:in `retry_with_backoff'","lib/gitlab/database/load_balancing/load_balancer.rb:110:in `read_write'","lib/gitlab/database/load_balancing/connection_proxy.rb:118:in `write_using_load_balancer'","lib/gitlab/database/load_balancing/connection_proxy.rb:70:in `transaction'","lib/gitlab/database.rb:290:in `block in transaction'","lib/gitlab/database.rb:289:in `transaction'","lib/tasks/gitlab/db.rake:104:in `block (3 levels) in \u003ctop (required)\u003e'"],"user.username":null,"tags.program":"web","tags.locale":"en","tags.feature_category":null,"tags.correlation_id":"41549056ab7dca97f88c80c05dabc5a1"}
{"severity":"ERROR","time":"2022-06-04T08:39:33.498Z","correlation_id":"41549056ab7dca97f88c80c05dabc5a1","exception.class":"Sidekiq::Worker::EnqueueFromTransactionError","exception.message":"`Projects::PostCreationWorker.perform_async` cannot be called inside a transaction as this can lead to\nrace conditions when the worker runs before the transaction is committed and\ntries to access a model that has not been saved yet.\n\nUse an `after_commit` hook, or include `AfterCommitQueue` and use a `run_after_commit` block instead.\n","exception.backtrace":["config/initializers/forbid_sidekiq_in_transactions.rb:25:in `block (2 levels) in \u003cmodule:NoEnqueueingFromTransactions\u003e'","app/services/projects/create_service.rb:128:in `after_create_actions'","app/services/projects/create_service.rb:76:in `block in execute'","lib/gitlab/application_context.rb:100:in `block in use'","lib/gitlab/application_context.rb:100:in `use'","lib/gitlab/application_context.rb:46:in `with_context'","app/services/projects/create_service.rb:75:in `execute'","app/services/concerns/measurable.rb:35:in `execute'","lib/gitlab/database_importers/self_monitoring/project/create_service.rb:59:in `create_project'","app/models/concerns/stepable.rb:14:in `call'","app/models/concerns/stepable.rb:14:in `block in execute_steps'","app/models/concerns/stepable.rb:13:in `each'","app/models/concerns/stepable.rb:13:in `inject'","app/models/concerns/stepable.rb:13:in `execute_steps'","lib/gitlab/database_importers/self_monitoring/project/create_service.rb:27:in `execute'","(eval):3:in `block (2 levels) in run_file'","lib/gitlab/database/load_balancing/connection_proxy.rb:119:in `block in write_using_load_balancer'","lib/gitlab/database/load_balancing/load_balancer.rb:112:in `block in read_write'","lib/gitlab/database/load_balancing/load_balancer.rb:172:in `retry_with_backoff'","lib/gitlab/database/load_balancing/load_balancer.rb:110:in `read_write'","lib/gitlab/database/load_balancing/connection_proxy.rb:118:in `write_using_load_balancer'","lib/gitlab/database/load_balancing/connection_proxy.rb:70:in `transaction'","lib/gitlab/database.rb:290:in `block in transaction'","lib/gitlab/database.rb:289:in `transaction'","lib/tasks/gitlab/db.rake:104:in `block (3 levels) in \u003ctop (required)\u003e'"],"user.username":null,"tags.program":"web","tags.locale":"en","tags.feature_category":null,"tags.correlation_id":"41549056ab7dca97f88c80c05dabc5a1"}
{"severity":"ERROR","time":"2022-06-04T08:39:33.664Z","correlation_id":"41549056ab7dca97f88c80c05dabc5a1","exception.class":"Gitlab::Git::PreReceiveError","exception.message":"Internal API unreachable","exception.backtrace":["lib/gitlab/gitaly_client/operation_service.rb:391:in `user_commit_files'","lib/gitlab/git/repository.rb:917:in `block in multi_action'","lib/gitlab/git/wraps_gitaly_errors.rb:7:in `wrapped_gitaly_errors'","lib/gitlab/git/repository.rb:916:in `multi_action'","app/models/repository.rb:846:in `block in multi_action'","app/models/repository.rb:829:in `with_cache_hooks'","app/models/repository.rb:846:in `multi_action'","app/models/repository.rb:804:in `create_file'","app/services/files/create_service.rb:16:in `create_transformed_commit'","app/services/files/create_service.rb:10:in `create_commit!'","app/services/commits/create_service.rb:30:in `execute'","app/services/projects/create_service.rb:182:in `create_readme'","app/services/projects/create_service.rb:130:in `after_create_actions'","app/services/projects/create_service.rb:76:in `block in execute'","lib/gitlab/application_context.rb:100:in `block in use'","lib/gitlab/application_context.rb:100:in `use'","lib/gitlab/application_context.rb:46:in `with_context'","app/services/projects/create_service.rb:75:in `execute'","app/services/concerns/measurable.rb:35:in `execute'","lib/gitlab/database_importers/self_monitoring/project/create_service.rb:59:in `create_project'","app/models/concerns/stepable.rb:14:in `call'","app/models/concerns/stepable.rb:14:in `block in execute_steps'","app/models/concerns/stepable.rb:13:in `each'","app/models/concerns/stepable.rb:13:in `inject'","app/models/concerns/stepable.rb:13:in `execute_steps'","lib/gitlab/database_importers/self_monitoring/project/create_service.rb:27:in `execute'","(eval):3:in `block (2 levels) in run_file'","lib/gitlab/database/load_balancing/connection_proxy.rb:119:in `block in write_using_load_balancer'","lib/gitlab/database/load_balancing/load_balancer.rb:112:in `block in read_write'","lib/gitlab/database/load_balancing/load_balancer.rb:172:in `retry_with_backoff'","lib/gitlab/database/load_balancing/load_balancer.rb:110:in `read_write'","lib/gitlab/database/load_balancing/connection_proxy.rb:118:in `write_using_load_balancer'","lib/gitlab/database/load_balancing/connection_proxy.rb:70:in `transaction'","lib/gitlab/database.rb:290:in `block in transaction'","lib/gitlab/database.rb:289:in `transaction'","lib/tasks/gitlab/db.rake:104:in `block (3 levels) in \u003ctop (required)\u003e'"],"user.username":null,"tags.program":"web","tags.locale":"en","tags.feature_category":null,"tags.correlation_id":"41549056ab7dca97f88c80c05dabc5a1"}
